create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text,
  description text,
  content text,
  content_hash text,
  word_count integer default 0,
  language text default 'unknown',
  updated_at timestamptz default now()
);
create index if not exists pages_updated_idx on public.pages(updated_at desc);
create index if not exists pages_hash_idx on public.pages(content_hash);

create table if not exists public.crawl_queue (
  id bigint generated by default as identity primary key,
  url text not null unique,
  status text not null default 'queued',
  last_crawled_at timestamptz,
  last_error text,
  created_at timestamptz default now()
);
create index if not exists crawl_queue_status_idx on public.crawl_queue(status);

alter table public.pages enable row level security;
alter table public.crawl_queue enable row level security;

create policy "public read pages" on public.pages for select to anon, authenticated using (true);
create policy "service pages all" on public.pages for all to service_role using (true) with check (true);
create policy "service queue all" on public.crawl_queue for all to service_role using (true) with check (true);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  url text not null unique,
  source_name text not null,
  source_domain text not null,
  published_at timestamptz,
  image_url text,
  fetched_at timestamptz default now()
);
create index if not exists news_published_idx on public.news(published_at desc);
create index if not exists news_source_idx on public.news(source_domain);
alter table public.news enable row level security;
create policy "public read news" on public.news for select to anon, authenticated using (true);
create policy "service news all" on public.news for all to service_role using (true) with check (true);
