-- HEXORA Search Engine
-- Supabase PostgreSQL schema
-- Worldwide crawler + search index

create extension if not exists pg_trgm;

-- =========================================================
-- PAGES
-- =========================================================

create table if not exists public.pages (
    id bigint generated by default as identity primary key,

    url text not null unique,

    title text default '',
    description text default '',
    content text default '',

    language text default 'en',

    author text,
    image_url text,

    published_at timestamptz,
    updated_at timestamptz,
    last_crawled_at timestamptz default now(),

    status_code integer default 200,

    content_hash text,

    created_at timestamptz default now(),

    search_vector tsvector
    generated always as (
        to_tsvector(
            'simple'::regconfig,
            coalesce(title, '') || ' ' ||
            coalesce(description, '') || ' ' ||
            coalesce(content, '') || ' ' ||
            coalesce(url, '')
        )
    ) stored
);

-- Full text search index
create index if not exists pages_search_vector_idx
on public.pages
using gin (search_vector);

-- Fast URL search
create index if not exists pages_url_idx
on public.pages using gin (url gin_trgm_ops);

-- Fast title search
create index if not exists pages_title_idx
on public.pages using gin (title gin_trgm_ops);

-- Language filtering
create index if not exists pages_language_idx
on public.pages(language);

-- Crawl freshness
create index if not exists pages_last_crawled_idx
on public.pages(last_crawled_at desc);

-- Published date
create index if not exists pages_published_idx
on public.pages(published_at desc);


-- =========================================================
-- CRAWL QUEUE
-- =========================================================

create table if not exists public.crawl_queue (
    id bigint generated by default as identity primary key,

    url text not null unique,

    status text not null default 'pending'
        check (status in ('pending', 'processing', 'done', 'failed')),

    priority integer default 0,

    discovered_from text,

    started_at timestamptz,
    finished_at timestamptz,

    error text,

    created_at timestamptz default now()
);

-- Queue indexes
create index if not exists crawl_queue_status_priority_idx
on public.crawl_queue(status, priority desc);

create index if not exists crawl_queue_created_idx
on public.crawl_queue(created_at);

create index if not exists crawl_queue_processing_idx
on public.crawl_queue(started_at);


-- =========================================================
-- NEWS
-- =========================================================

create table if not exists public.news (
    id bigint generated by default as identity primary key,

    url text not null unique,

    title text default '',
    description text default '',
    content text default '',

    source text,
    image_url text,

    language text default 'en',

    published_at timestamptz,

    created_at timestamptz default now()
);

create index if not exists news_published_idx
on public.news(published_at desc);

create index if not exists news_language_idx
on public.news(language);

create index if not exists news_title_idx
on public.news using gin (title gin_trgm_ops);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.pages enable row level security;
alter table public.crawl_queue enable row level security;
alter table public.news enable row level security;


-- Public search/read access
drop policy if exists "Public can read pages" on public.pages;

create policy "Public can read pages"
on public.pages
for select
to anon, authenticated
using (true);


drop policy if exists "Public can read news" on public.news;

create policy "Public can read news"
on public.news
for select
to anon, authenticated
using (true);


-- Crawl queue is server-side only.
-- Service-role bypasses RLS automatically.


-- =========================================================
-- SEED FUNCTION
-- =========================================================

create or replace function public.hexora_queue_seed(
    seed_url text,
    seed_priority integer default 100
)
returns void
language plpgsql
security definer
as $$
begin

    insert into public.crawl_queue (
        url,
        status,
        priority
    )
    values (
        seed_url,
        'pending',
        seed_priority
    )
    on conflict (url)
    do update set
        priority = greatest(
            public.crawl_queue.priority,
            excluded.priority
        );

end;
$$;


-- =========================================================
-- BASIC HEALTH VIEW
-- =========================================================

create or replace view public.hexora_stats as
select
    (select count(*) from public.pages) as total_pages,
    (select count(*) from public.crawl_queue) as total_queue,
    (select count(*) from public.crawl_queue where status = 'pending') as pending_queue,
    (select count(*) from public.crawl_queue where status = 'processing') as processing_queue,
    (select count(*) from public.crawl_queue where status = 'done') as completed_queue,
    (select count(*) from public.crawl_queue where status = 'failed') as failed_queue,
    (select count(*) from public.news) as total_news;


-- =========================================================
-- INITIAL SEEDS
-- =========================================================

insert into public.crawl_queue (url, status, priority)
values
    ('https://www.wikipedia.org/', 'pending', 100),
    ('https://www.w3.org/', 'pending', 100),
    ('https://www.iana.org/', 'pending', 100),
    ('https://www.mozilla.org/', 'pending', 100),
    ('https://archive.org/', 'pending', 100),
    ('https://www.britannica.com/', 'pending', 100),
    ('https://github.com/', 'pending', 100),
    ('https://www.reddit.com/', 'pending', 90),
    ('https://www.india.gov.in/', 'pending', 100),
    ('https://assam.gov.in/', 'pending', 100)
on conflict (url)
do nothing;
