-- =========================================================
-- HEXORA SEARCH SCHEMA UPGRADE
-- =========================================================

-- Ensure required extension
create extension if not exists pg_trgm;


-- =========================================================
-- EXTRA SEARCH INDEXES
-- =========================================================

create index if not exists pages_description_idx
on public.pages using gin (description gin_trgm_ops);

create index if not exists pages_content_idx
on public.pages using gin (content gin_trgm_ops);


-- =========================================================
-- DOMAIN EXTRACTION
-- =========================================================

alter table public.pages
add column if not exists domain text;

update public.pages
set domain =
    regexp_replace(
        regexp_replace(url, '^https?://', ''),
        '/.*$',
        ''
    )
where domain is null;


create index if not exists pages_domain_idx
on public.pages(domain);


-- =========================================================
-- CRAWL PRIORITY SUPPORT
-- =========================================================

alter table public.crawl_queue
add column if not exists attempts integer default 0;

alter table public.crawl_queue
add column if not exists next_crawl_at timestamptz;


create index if not exists crawl_queue_next_crawl_idx
on public.crawl_queue(next_crawl_at);


-- =========================================================
-- SEARCH STATISTICS
-- =========================================================

create table if not exists public.search_logs (
    id bigint generated by default as identity primary key,

    query text not null,

    result_count integer default 0,

    created_at timestamptz default now()
);

create index if not exists search_logs_created_idx
on public.search_logs(created_at desc);

create index if not exists search_logs_query_idx
on public.search_logs(query);


-- =========================================================
-- LINK GRAPH
-- =========================================================

create table if not exists public.page_links (
    id bigint generated by default as identity primary key,

    source_url text not null,

    target_url text not null,

    anchor_text text default '',

    created_at timestamptz default now(),

    unique(source_url, target_url)
);

create index if not exists page_links_source_idx
on public.page_links(source_url);

create index if not exists page_links_target_idx
on public.page_links(target_url);


-- =========================================================
-- PAGE AUTHORITY
-- =========================================================

alter table public.pages
add column if not exists authority_score double precision default 0;

alter table public.pages
add column if not exists popularity_score double precision default 0;


create index if not exists pages_authority_idx
on public.pages(authority_score desc);


-- =========================================================
-- SEARCH ENGINE SETTINGS
-- =========================================================

create table if not exists public.hexora_settings (
    key text primary key,
    value text,
    updated_at timestamptz default now()
);

insert into public.hexora_settings(key, value)
values
    ('engine_name', 'HEXORA'),
    ('crawler_enabled', 'true'),
    ('search_enabled', 'true'),
    ('default_language', 'all')
on conflict (key)
do nothing;
